export const data = [
  {
    id: 1,
    title: "super man",
    category: "Mistery",
    rate: 6,
    cover:
      "https://c8.alamy.com/compfr/f3cfw2/superman-returns-2006-film-avec-brandon-routh-f3cfw2.jpg",
    cast: "Lana Lang, Justice League, Man of Steel",
    release: "13 décembre 1978 ",
    Description: "description",
  },
  {
    id: 2,
    title: "The Hateful Eight",
    category: "War",
    rate: 6,
    cover: "https://fr.web.img6.acsta.net/pictures/22/06/08/09/58/5593435.jpg",
    cast: "Samuel L.Jackson, Kurt Russel, Jennifer Jason Leigh",
    release: "2015-12-30 ",
    Description: "description",
  },
  {
    id: 3,
    title: "Once Upon a Time in Hollywood",
    category: "Drama",
    rate: 7,
    cover:
      "https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_FMjpg_UX1000_.jpg",
    cast: "Leonardo DiCaprio, Brad Pitt, Margot Robbie",
    release: "2019-07-26",
    Description: "description",
  },
  {
    id: 4,
    title: "Inglourious Basterds",
    category: "War",
    rate: 8,
    cover: "https://m.media-amazon.com/images/I/61PXdxTJGPL._AC_SY741_.jpg",
    cast: " Brad Pitt, Diane Kruger, Eli Roth",
    release: "2009-08-20",
    Description: "description",
  },
  {
    id: 5,
    title: "Kill Bill Vol. 1",
    category: "Crime",
    rate: 9,
    cover: "https://m.media-amazon.com/images/I/81Az82YYZaS._AC_SL1500_.jpg",
    cast: " Uma Thurman, David Carradine, Daryl Hannah",
    release: " 21 janvier 2022",
    Description: "description",
  },
  {
    id: 6,
    title: "Cheval de guerre",
    category: "Drama",
    rate: 5,
    cover:
      "https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/83/47/99/19825088.jpg",
    cast: "Jeremy Irvine, Peter Mullan, Samuel Lz. Jackson",
    release: "25 décembre 2011",
    Description: "description",
  },
  {
    id: 7,
    title: "Jackie Brown",
    category: "Crime",
    rate: 6,
    cover:
      "https://cdn.shopify.com/s/files/1/1416/8662/products/JackieBrown_1997_original_film_art_bcad0eb7-06a6-46e0-9e36-b1de44cf3036_1200x.jpg?v=1643239190",
    cast: "Pam Grier, Samuel L. Jackson, Robert Forster",
    release: "1997-12-25",
    Description: "description",
  },
  {
    id: 8,
    title: "Kill Bill 2",
    category: "Crime",
    rate: 8,
    cover:
      "https://c8.alamy.com/comp/BKGG4D/kill-bill-volume-2-2004-poster-kbl2-002-post1-BKGG4D.jpg",
    cast: "Uma Thurman, David Carradine, Michael Madsen",
    release: "2004-04-16",
    Description: "description",
  },
];
